# This is a basic workflow to help you get started with Actions

name: Autodeploy

# Controls when the workflow will run
on:
  # Triggers autodeploy on push to master
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.13.1
      - name: Install dependencies
        run: scripts/install.sh
      - name: Build
        run: scripts/build.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build # build must succeed before deployment
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          port: 22
          args: --script "'cd project-echo/ && git pull && pm2 startOrReload ecosystem.config.js'"
#       - name: Purge Cloudflare cache
#         uses: jakejarvis/cloudflare-purge-action@master
#         if: success()
#         env:
#           CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
#           CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
